### ISSUE TITLE
post to sessions not working from FE

### ISSUE THREAD

**Issue by chriscamac** [J-Graham/TrainingRaterStarter#1]
when posting to the sessions route in the api from postman, I can create a session record.  But when I do it from the angular service, it is throwing an error

![image](https://user-images.githubusercontent.com/19155541/48624108-97afde00-e979-11e8-8640-9a94661bd115.png)

**Comment by J-Graham** [comment]
This issue has been corrected in the following commit: https://github.com/J-Graham/TrainingRaterStarter/commit/54f46c7f129cbdb34f05779ec9c6b38e1c39a81e
There were some additional configurations needed in the app.js
